import type { Stadium } from "./types";

export const mockStadiums: Stadium[] = [
  {
    id: "stade-al-wahda",
    name: "Stade Al Wahda",
    city: "Beni Mellal",
    distanceKm: 2.1,
    pricePerHour: 250,
    rating: 4.9,
    reviewCount: 128,
    openUntil: "23:00",
    facilities: ["floodlights", "parking", "showers"],
    badge: "Top rated",
    isFavorite: false,
  },
  {
    id: "green-arena",
    name: "Green Arena",
    city: "Beni Mellal",
    distanceKm: 3.4,
    pricePerHour: 180,
    rating: 4.6,
    reviewCount: 74,
    openUntil: "22:00",
    facilities: ["parking", "turf"],
    isFavorite: false,
  },
  {
    id: "royal-arena",
    name: "Royal Arena",
    city: "Beni Mellal",
    distanceKm: 5.0,
    pricePerHour: 300,
    rating: 4.8,
    reviewCount: 96,
    openUntil: "00:00",
    facilities: ["floodlights", "turf", "changing-rooms"],
    badge: "New",
    isFavorite: true,
  },
  {
    id: "stade-atlas",
    name: "Stade Atlas",
    city: "Kasba Tadla",
    distanceKm: 22,
    pricePerHour: 150,
    rating: 4.3,
    reviewCount: 41,
    openUntil: "21:00",
    facilities: ["parking"],
    isFavorite: false,
  },
  {
    id: "al-amal-sport",
    name: "Al Amal Sport",
    city: "Fkih Ben Salah",
    distanceKm: 30,
    pricePerHour: 220,
    rating: 4.5,
    reviewCount: 58,
    openUntil: "23:30",
    facilities: ["floodlights", "changing-rooms"],
    isFavorite: false,
  },
  {
    id: "complexe-ennasr",
    name: "Complexe Ennasr",
    city: "Beni Mellal",
    distanceKm: 6.7,
    pricePerHour: 200,
    rating: 4.4,
    reviewCount: 63,
    openUntil: "22:00",
    facilities: ["parking", "turf"],
    isFavorite: false,
  },
];
